apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: backend.playlinegames.net
    http:
      paths:
      - path: /time
        pathType: Prefix
        backend:
          service:
            name: setup-service
            port:
              number: 8080
      - path: /new-game
        pathType: Prefix
        backend:
          service:
            name: setup-service
            port:
              number: 8080
      - path: /delete-game
        pathType: Prefix
        backend:
          service:
            name: setup-service
            port:
              number: 8080
      - path: /request-seat
        pathType: Prefix
        backend:
          service:
            name: setup-service
            port:
              number: 8080
      - path: /empty-seats
        pathType: Prefix
        backend:
          service:
            name: setup-service
            port:
              number: 8080
      - path: /ai-seats
        pathType: Prefix
        backend:
          service:
            name: setup-service
            port:
              number: 8080
      - path: /games-list
        pathType: Prefix
        backend:
          service:
            name: lobby-service
            port:
              number: 1111
      - path: /make-move
        pathType: Prefix
        backend:
          service:
            name: gameplay-service
            port:
              number: 3333
      - path: /request-move
        pathType: Prefix
        backend:
          service:
            name: gameplay-service
            port:
              number: 3333
