apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://playlinegames.net/*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,X-LANG,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,X-Api-Key,X-Device-Id,Access-Control-Allow-Origin"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - backend.playlinegames.net
    secretName: backend-tls
  rules:
  - host: backend.playlinegames.net
    http:
      paths:
      - path: /new-game
        pathType: Prefix
        backend:
          service:
            name: setup-service
            port:
              number: 8080
      - path: /delete-game
        pathType: Prefix
        backend:
          service:
            name: setup-service
            port:
              number: 8080
      - path: /request-seat
        pathType: Prefix
        backend:
          service:
            name: setup-service
            port:
              number: 8080
      - path: /empty-seats
        pathType: Prefix
        backend:
          service:
            name: setup-service
            port:
              number: 8080
      - path: /ai-seats
        pathType: Prefix
        backend:
          service:
            name: setup-service
            port:
              number: 8080
      - path: /games-list
        pathType: Prefix
        backend:
          service:
            name: lobby-service
            port:
              number: 1111
      - path: /make-move
        pathType: Prefix
        backend:
          service:
            name: gameplay-service
            port:
              number: 3333
      - path: /request-move
        pathType: Prefix
        backend:
          service:
            name: gameplay-service
            port:
              number: 3333
