apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: db-volume-claim
spec:
    accessModes:
      - ReadWriteOnce   # Accessed by at most one node at a time
                        # See https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
    resources:
        requests:
            storage: 16Gi
